PropertyAccess is required not only in dev
If Exporter is used without PropertyAccess, the following exception is thrown:

```
Fatal error: Class 'Symfony\Component\PropertyAccess\PropertyAccess' not found in /(...)/vendor/sonata-project/exporter/lib/Exporter/Source/DoctrineORMQuerySourceIterator.php on line 57
```

This happens in Symfony 2.1, where PropertyAccess didn't exist yet.